[build]
  functions = "functions"
  command = "npm run build"

[dev]
  framework = "#static"
  targetPort = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"